### ISSUE TITLE
I temporarily broke OAuth

### ISSUE THREAD

**Issue by copperwall** [sccalabr/cpe409-final-project#1]
Fix coming soon.

**Comment by sccalabr** [comment]
I'm not sure if I can reply to the git hub email. The commit was intentional. Everything was working when we did the commit

**Comment by copperwall** [comment]
I amended a bunch of errors in 99b649b308c2c933ef16a8d525f92e7eda871ed2. Is something not working the way we expected?

**Comment by sccalabr** [comment]
Not that I am aware of. This commit just pulled data from the database and displayed it in the feed for subreddits and for followers.

**Comment by copperwall** [comment]
oh yeah, I was just joking about how the comment still said the cookie would last 60 seconds, when the actual value was changed to 36000 seconds.
