### ISSUE TITLE
Settings needs a route(s) and a Library.

### ISSUE THREAD

**Issue by copperwall** [sccalabr/cpe409-final-project#2]
@sccalabr @who03 Should adding a setting through the UI be through AJAX or through an HTML form?

**Comment by sccalabr** [comment]
Does it matter? I'm partial to Ajax but I think either would work.

**Comment by copperwall** [comment]
No too much I guess, AJAX sounds good to me too.

**Comment by copperwall** [comment]
Following users through the UI is done, but sliders haven't been working, so that part isn't complete yet. The backend for adding subreddits should be all good though.

**Comment by copperwall** [comment]
This is done. The subreddit preference is respected now too.
