### ISSUE TITLE
Timestamping the comments/posts would be cool

### ISSUE THREAD

**Issue by copperwall** [sccalabr/cpe409-final-project#4]
It'd be nice to tell the user how much time has passed since a comment or post has been posted. Shouldn't be too hard to do something in JS, since the data from the API is timestamped.

**Comment by sccalabr** [comment]
Do you mean the post that get displayed or the messages they make?

**Comment by copperwall** [comment]
Oops, that was worded poorly. I meant that the timestamp should be on the comments and subreddit posts. I updated the description.

**Comment by copperwall** [comment]
Added in 7b41b33ab2a6a14e04ced94b06d1811381e3687d
