### ISSUE TITLE
Implement Messaging

### ISSUE THREAD

**Issue by copperwall** [sccalabr/cpe409-final-project#5]
So it seems that the CAPTCHA is only required if the user is new enough that reddit feels they are probably a bot. As far as the milestone goes, I think we would could ignore this and assume that the person will not be required to use the CAPTCHA and still be able to post the message.

**Comment by sccalabr** [comment]
That seems like a safe assumption to me. Our application is only for die hard users.

**Comment by copperwall** [comment]
Merged with 00a9ffd5cd4efdfbc1336770304f08bf1e67128c.
