### ISSUE TITLE
Disable tab buttons while the content is loading

### ISSUE THREAD

**Issue by copperwall** [sccalabr/cpe409-final-project#7]
So the UI sort of breaks in an ugly way if you click on another tab while it is still loading things. This can be fixed by disabling button events until everything has finished loading.

**Comment by sccalabr** [comment]
I agree, can I close everything on taiga now? Jay said that is what he is going to use to grade should be working

**Comment by copperwall** [comment]
Yep! Everything on taiga should be good.

**Comment by copperwall** [comment]
This was also addressed in 2ed7fae9c5e675f3ed65ceed1ba618f4fb9c471d.
